[stdlog] 2022-10-28 21:02:43,335 avocado.test INFO | INIT 1-tests/system_base/util-linux/tc_ag_util-linux_mkswap_fun_004.py:Test.test
[stdlog] 2022-10-28 21:02:43,336 avocado.test DEBUG| PARAMS (key=timeout, path=*, default=None) => None
[stdlog] 2022-10-28 21:02:43,336 avocado.test DEBUG| Test metadata:
[stdlog] 2022-10-28 21:02:43,336 avocado.test DEBUG|   filename: /root/GitRepo/anolis-pkg-tests/tests/system_base/util-linux/tc_ag_util-linux_mkswap_fun_004.py
[stdlog] 2022-10-28 21:02:43,336 avocado.test DEBUG|   teststmpdir: /var/tmp/avocado_cmoau920
[stdlog] 2022-10-28 21:02:43,336 avocado.test INFO | START 1-tests/system_base/util-linux/tc_ag_util-linux_mkswap_fun_004.py:Test.test
[stdlog] 2022-10-28 21:02:43,336 avocado.test INFO | setup
[stdlog] 2022-10-28 21:02:43,336 avocado.test DEBUG| PARAMS (key=remote, path=*, default=None) => None
[stdlog] 2022-10-28 21:02:43,337 avocado.utils.process INFO | Running 'rpm -q util-linux'
[stdlog] 2022-10-28 21:02:43,344 avocado.utils.process DEBUG| [stdout] util-linux-2.32.1-35.0.1.an8.x86_64
[stdlog] 2022-10-28 21:02:43,345 avocado.utils.process INFO | Command 'rpm -q util-linux' finished with 0 after 0.007221407s
[stdlog] 2022-10-28 21:02:43,345 avocado.utils.process INFO | Running 'yum update util-linux -y'
[stdlog] 2022-10-28 21:02:43,631 avocado.utils.process DEBUG| [stdout] Last metadata expiration check: 2:45:11 ago on Fri 28 Oct 2022 06:17:32 PM CST.
[stdlog] 2022-10-28 21:02:43,899 avocado.utils.process DEBUG| [stdout] Dependencies resolved.
[stdlog] 2022-10-28 21:02:43,900 avocado.utils.process DEBUG| [stdout] Nothing to do.
[stdlog] 2022-10-28 21:02:43,901 avocado.utils.process DEBUG| [stdout] Complete!
[stdlog] 2022-10-28 21:02:44,218 avocado.utils.process INFO | Command 'yum update util-linux -y' finished with 0 after 0.872393572s
[stdlog] 2022-10-28 21:02:44,218 avocado.utils.process INFO | Running 'sudo mkswap -L {{swap1}} {{path/to/file}}'
[stdlog] 2022-10-28 21:02:44,229 avocado.utils.process DEBUG| [stderr] mkswap: 
[stdlog] 2022-10-28 21:02:44,229 avocado.utils.process DEBUG| [stderr] cannot open {{path/to/file}}
[stdlog] 2022-10-28 21:02:44,229 avocado.utils.process DEBUG| [stderr] : 
[stdlog] 2022-10-28 21:02:44,229 avocado.utils.process DEBUG| [stderr] No such file or directory
[stdlog] 2022-10-28 21:02:44,230 avocado.utils.process INFO | Command 'sudo mkswap -L {{swap1}} {{path/to/file}}' finished with 1 after 0.010814055s
[stdlog] 2022-10-28 21:02:44,230 avocado.test ERROR| 
[stdlog] 2022-10-28 21:02:44,230 avocado.test ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:761
[stdlog] 2022-10-28 21:02:44,231 avocado.test ERROR| Traceback (most recent call last):
[stdlog] 2022-10-28 21:02:44,231 avocado.test ERROR|   File "/root/GitRepo/anolis-pkg-tests/tests/system_base/util-linux/tc_ag_util-linux_mkswap_fun_004.py", line 27, in test
[stdlog] 2022-10-28 21:02:44,231 avocado.test ERROR|     ret_c, ret_o = self.cmd("sudo mkswap -L {{swap1}} {{path/to/file}}")
[stdlog] 2022-10-28 21:02:44,231 avocado.test ERROR|   File "/root/GitRepo/anolis-pkg-tests/tests/common/basetest.py", line 54, in cmd
[stdlog] 2022-10-28 21:02:44,231 avocado.test ERROR|     return self.local.cmd(command, ignore_status=ignore_status)
[stdlog] 2022-10-28 21:02:44,231 avocado.test ERROR|   File "/root/GitRepo/anolis-pkg-tests/tests/common/hosts.py", line 45, in cmd
[stdlog] 2022-10-28 21:02:44,231 avocado.test ERROR|     result = process.run(command, ignore_status=ignore_status, shell=True)
[stdlog] 2022-10-28 21:02:44,231 avocado.test ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1015, in run
[stdlog] 2022-10-28 21:02:44,231 avocado.test ERROR|     raise CmdError(cmd, sp.result)
[stdlog] 2022-10-28 21:02:44,231 avocado.test ERROR| avocado.utils.process.CmdError: Command 'sudo mkswap -L {{swap1}} {{path/to/file}}' failed.
[stdlog] 2022-10-28 21:02:44,231 avocado.test ERROR| stdout: b''
[stdlog] 2022-10-28 21:02:44,231 avocado.test ERROR| stderr: b'mkswap: cannot open {{path/to/file}}: No such file or directory\n'
[stdlog] 2022-10-28 21:02:44,231 avocado.test ERROR| additional_info: None
[stdlog] 2022-10-28 21:02:44,231 avocado.test ERROR| 
[stdlog] 2022-10-28 21:02:44,231 avocado.test DEBUG| Local variables:
[stdlog] 2022-10-28 21:02:44,243 avocado.test DEBUG|  -> self <class 'tc_ag_util-linux_mkswap_fun_004.Test'>: 1-tests/system_base/util-linux/tc_ag_util-linux_mkswap_fun_004.py:Test.test
[stdlog] 2022-10-28 21:02:44,243 avocado.test INFO | teardown
[stdlog] 2022-10-28 21:02:44,243 avocado.utils.process INFO | Running 'yum erase  -y'
[stdlog] 2022-10-28 21:02:44,526 avocado.utils.process DEBUG| [stderr] No packages marked for removal.
[stdlog] 2022-10-28 21:02:44,533 avocado.utils.process DEBUG| [stdout] Dependencies resolved.
[stdlog] 2022-10-28 21:02:44,534 avocado.utils.process DEBUG| [stdout] Nothing to do.
[stdlog] 2022-10-28 21:02:44,534 avocado.utils.process DEBUG| [stdout] Complete!
[stdlog] 2022-10-28 21:02:44,814 avocado.utils.process INFO | Command 'yum erase  -y' finished with 0 after 0.570122421s
[stdlog] 2022-10-28 21:02:44,815 avocado.test ERROR| Traceback (most recent call last):
[stdlog] 2022-10-28 21:02:44,815 avocado.test ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 796, in _run_avocado
[stdlog]     raise test_exception
[stdlog] 2022-10-28 21:02:44,815 avocado.test ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 756, in _run_avocado
[stdlog]     testMethod()
[stdlog] 2022-10-28 21:02:44,815 avocado.test ERROR|   File "/root/GitRepo/anolis-pkg-tests/tests/system_base/util-linux/tc_ag_util-linux_mkswap_fun_004.py", line 27, in test
[stdlog]     ret_c, ret_o = self.cmd("sudo mkswap -L {{swap1}} {{path/to/file}}")
[stdlog] 2022-10-28 21:02:44,815 avocado.test ERROR|   File "/root/GitRepo/anolis-pkg-tests/tests/common/basetest.py", line 54, in cmd
[stdlog]     return self.local.cmd(command, ignore_status=ignore_status)
[stdlog] 2022-10-28 21:02:44,815 avocado.test ERROR|   File "/root/GitRepo/anolis-pkg-tests/tests/common/hosts.py", line 45, in cmd
[stdlog]     result = process.run(command, ignore_status=ignore_status, shell=True)
[stdlog] 2022-10-28 21:02:44,815 avocado.test ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1015, in run
[stdlog]     raise CmdError(cmd, sp.result)
[stdlog] 2022-10-28 21:02:44,815 avocado.test ERROR| avocado.utils.process.CmdError: Command 'sudo mkswap -L {{swap1}} {{path/to/file}}' failed.
[stdlog] stdout: b''
[stdlog] stderr: b'mkswap: cannot open {{path/to/file}}: No such file or directory\n'
[stdlog] additional_info: None
[stdlog] 2022-10-28 21:02:44,815 avocado.test ERROR| ERROR 1-tests/system_base/util-linux/tc_ag_util-linux_mkswap_fun_004.py:Test.test -> CmdError: Command 'sudo mkswap -L {{swap1}} {{path/to/file}}' failed.
[stdlog] stdout: b''
[stdlog] stderr: b'mkswap: cannot open {{path/to/file}}: No such file or directory\n'
[stdlog] additional_info: None
[stdlog] 2022-10-28 21:02:44,815 avocado.test INFO | 
