+ source ./common/disk_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment!'
+ message='Start to prepare the test environment!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment!'
Wed Dec  7 08:41:44 2022 - INFO  - Start to prepare the test environment!
+ DNF_INSTALL lvm2
+ pkgs=lvm2
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs lvm2 --node 1 --tempfile ''
Wed Dec  7 08:41:52 2022 - INFO  - pkgs:(lvm2) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ check_free_disk
++ TEST_DISK
++ id=1
++ python3 /root/mugen-riscv/libs/locallibs/get_test_device.py --device disk --node 1
+ disks=
+ disk_list=($disks)
+ local_disk=
+ local_disk1=
+ local_disk2=
+ local_disk3=
++ cat /etc/os-release
++ grep VERSION_ID
++ awk -F = '{print$NF}'
++ awk -F '"' '{print$2}'
+ version_id=8.5
+ LOG_INFO 'End to prepare the test environment!'
+ message='End to prepare the test environment!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment!'
Wed Dec  7 08:41:58 2022 - INFO  - End to prepare the test environment!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase!'
+ message='Start executing testcase!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase!'
Wed Dec  7 08:41:59 2022 - INFO  - Start executing testcase!
+ pvcreate -y /dev/
  No device found for /dev/.
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvresize_001.sh line 31'
+ message='oe_test_lvm2_pvresize_001.sh line 31'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvresize_001.sh line 31'
Wed Dec  7 08:41:59 2022 - ERROR - oe_test_lvm2_pvresize_001.sh line 31
+ return 0
+ pvresize -y /dev/ --setphysicalvolumesize 50MB
+ grep 'Physical volume "/dev/" changed'
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvresize_001.sh line 33'
+ message='oe_test_lvm2_pvresize_001.sh line 33'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvresize_001.sh line 33'
Wed Dec  7 08:42:00 2022 - ERROR - oe_test_lvm2_pvresize_001.sh line 33
+ return 0
+ pvs
+ sed -n 3p
+ awk '{print$5}'
+ grep 50.00m
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvresize_001.sh line 35'
+ message='oe_test_lvm2_pvresize_001.sh line 35'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvresize_001.sh line 35'
Wed Dec  7 08:42:01 2022 - ERROR - oe_test_lvm2_pvresize_001.sh line 35
+ return 0
+ pvresize -y /dev/ --reportformat basic
+ grep 'Physical volume "/dev/" changed'
  Cannot use /dev/: device not found
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvresize_001.sh line 37'
+ message='oe_test_lvm2_pvresize_001.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvresize_001.sh line 37'
Wed Dec  7 08:42:02 2022 - ERROR - oe_test_lvm2_pvresize_001.sh line 37
+ return 0
+ pvresize -y /dev/ --driverloaded y
+ grep 'Physical volume "/dev/" changed'
  Cannot use /dev/: device not found
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvresize_001.sh line 39'
+ message='oe_test_lvm2_pvresize_001.sh line 39'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvresize_001.sh line 39'
Wed Dec  7 08:42:03 2022 - ERROR - oe_test_lvm2_pvresize_001.sh line 39
+ return 0
+ pvresize --version
+ grep 'LVM version'
  LVM version:     2.03.11(2) (2021-01-08)
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ pvresize --longhelp
+ grep 'Common variables for lvm'
  Common variables for lvm:
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ pvresize -y /dev/ --nolocking
+ grep 'Physical volume "/dev/" changed'
  WARNING: File locking is disabled.
  Cannot use /dev/: device not found
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvresize_001.sh line 45'
+ message='oe_test_lvm2_pvresize_001.sh line 45'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvresize_001.sh line 45'
Wed Dec  7 08:42:04 2022 - ERROR - oe_test_lvm2_pvresize_001.sh line 45
+ return 0
+ pvresize -y /dev/ -q
+ grep 'Physical volume "/dev/" changed'
  Cannot use /dev/: device not found
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvresize_001.sh line 47'
+ message='oe_test_lvm2_pvresize_001.sh line 47'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvresize_001.sh line 47'
Wed Dec  7 08:42:05 2022 - ERROR - oe_test_lvm2_pvresize_001.sh line 47
+ return 0
+ pvresize -y /dev/ --verbose
+ grep 'Physical volume "/dev/" changed'
  Cannot use /dev/: device not found
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvresize_001.sh line 49'
+ message='oe_test_lvm2_pvresize_001.sh line 49'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvresize_001.sh line 49'
Wed Dec  7 08:42:06 2022 - ERROR - oe_test_lvm2_pvresize_001.sh line 49
+ return 0
+ '[8.5' = '22.03]'
oe_test_lvm2_pvresize_001.sh: line 50: [8.5: command not found
+ LOG_INFO 'End executing testcase!'
+ message='End executing testcase!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End executing testcase!'
Wed Dec  7 08:42:07 2022 - INFO  - End executing testcase!
+ CASE_RESULT 0
+ case_re=0
+ test -z 8
+ test 8 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Dec  7 08:42:07 2022 - ERROR - failed to execute the case.
+ exit 8
+ post_test
+ LOG_INFO 'Start environment cleanup.'
+ message='Start environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environment cleanup.'
Wed Dec  7 08:42:08 2022 - INFO  - Start environment cleanup.
+ pvremove -f /dev/
  No device found for /dev/.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Wed Dec  7 08:42:09 2022 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'Finish environment cleanup.'
+ message='Finish environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup.'
Wed Dec  7 08:42:09 2022 - INFO  - Finish environment cleanup.
