+ source ../common/common_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Wed Dec  7 09:06:33 2022 - INFO  - Start environmental preparation.
+ DNF_INSTALL 'lxcfs lxcfs-tools'
+ pkgs='lxcfs lxcfs-tools'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs 'lxcfs lxcfs-tools' --node 1 --tempfile ''
Wed Dec  7 09:06:45 2022 - ERROR - pkgs:(lxcfs-tools) not found
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Wed Dec  7 09:06:46 2022 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Wed Dec  7 09:06:47 2022 - INFO  - Start testing...
+ test_execution lxcfs.service
+ service=lxcfs.service
++ date '+%Y-%m-%d %T'
+ log_time='2022-12-07 09:06:47'
+ test_restart lxcfs.service
+ service=lxcfs.service
+ systemctl restart lxcfs.service
Failed to restart lxcfs.service: Unit lxcfs.service not found.
+ CHECK_RESULT 5 0 0 'lxcfs.service restart failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service restart failed'
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'lxcfs.service restart failed'
+ LOG_ERROR 'lxcfs.service restart failed'
+ message='lxcfs.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'lxcfs.service restart failed'
Wed Dec  7 09:06:49 2022 - ERROR - lxcfs.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 34'
+ message='../common/common_lib.sh line 34'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 34'
Wed Dec  7 09:06:49 2022 - ERROR - ../common/common_lib.sh line 34
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ grep 'Active: active'
+ systemctl status lxcfs.service
Unit lxcfs.service could not be found.
+ CHECK_RESULT 1 0 0 'lxcfs.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service restart failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'lxcfs.service restart failed'
+ LOG_ERROR 'lxcfs.service restart failed'
+ message='lxcfs.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'lxcfs.service restart failed'
Wed Dec  7 09:06:56 2022 - ERROR - lxcfs.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 37'
+ message='../common/common_lib.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 37'
Wed Dec  7 09:06:56 2022 - ERROR - ../common/common_lib.sh line 37
+ return 0
+ systemctl stop lxcfs.service
Failed to stop lxcfs.service: Unit lxcfs.service not loaded.
+ CHECK_RESULT 5 0 0 'lxcfs.service stop failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service stop failed'
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'lxcfs.service stop failed'
+ LOG_ERROR 'lxcfs.service stop failed'
+ message='lxcfs.service stop failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'lxcfs.service stop failed'
Wed Dec  7 09:06:57 2022 - ERROR - lxcfs.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 39'
+ message='../common/common_lib.sh line 39'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 39'
Wed Dec  7 09:06:58 2022 - ERROR - ../common/common_lib.sh line 39
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status lxcfs.service
+ grep 'Active: inactive'
Unit lxcfs.service could not be found.
+ CHECK_RESULT 1 0 0 'lxcfs.service stop failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service stop failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'lxcfs.service stop failed'
+ LOG_ERROR 'lxcfs.service stop failed'
+ message='lxcfs.service stop failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'lxcfs.service stop failed'
Wed Dec  7 09:07:04 2022 - ERROR - lxcfs.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 42'
+ message='../common/common_lib.sh line 42'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 42'
Wed Dec  7 09:07:05 2022 - ERROR - ../common/common_lib.sh line 42
+ return 0
+ systemctl start lxcfs.service
Failed to start lxcfs.service: Unit lxcfs.service not found.
+ CHECK_RESULT 5 0 0 'lxcfs.service start failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service start failed'
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'lxcfs.service start failed'
+ LOG_ERROR 'lxcfs.service start failed'
+ message='lxcfs.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'lxcfs.service start failed'
Wed Dec  7 09:07:05 2022 - ERROR - lxcfs.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 44'
+ message='../common/common_lib.sh line 44'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 44'
Wed Dec  7 09:07:06 2022 - ERROR - ../common/common_lib.sh line 44
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status lxcfs.service
+ grep 'Active: active'
Unit lxcfs.service could not be found.
+ CHECK_RESULT 1 0 0 'lxcfs.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service start failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'lxcfs.service start failed'
+ LOG_ERROR 'lxcfs.service start failed'
+ message='lxcfs.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'lxcfs.service start failed'
Wed Dec  7 09:07:12 2022 - ERROR - lxcfs.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 47'
+ message='../common/common_lib.sh line 47'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 47'
Wed Dec  7 09:07:13 2022 - ERROR - ../common/common_lib.sh line 47
+ return 0
+ test_enabled lxcfs.service
+ service=lxcfs.service
++ systemctl is-enabled lxcfs.service
Failed to get unit file state for lxcfs.service: No such file or directory
+ state=
+ '[' '' == enabled ']'
+ '[' '' == disabled ']'
+ '[' '' == masked ']'
+ '[' '' == static ']'
+ LOG_INFO 'Unit is indirect, ignoring.'
+ message='Unit is indirect, ignoring.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Unit is indirect, ignoring.'
Wed Dec  7 09:07:14 2022 - INFO  - Unit is indirect, ignoring.
+ journalctl --since '2022-12-07 09:06:47' -u lxcfs.service
+ grep -i 'fail\|error'
+ grep -v -i 'DEBUG\|INFO\|WARNING'
+ CHECK_RESULT 1 0 1 'There is an error message for the log of lxcfs.service'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of lxcfs.service'
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ systemctl start lxcfs.service
Failed to start lxcfs.service: Unit lxcfs.service not found.
+ sed -i 's\ExecStart=/usr/bin/lxcfs\ExecStart=/usr/bin/lxcfs -d\g' /usr/lib/systemd/system/lxcfs.service
sed: can't read /usr/lib/systemd/system/lxcfs.service: No such file or directory
+ systemctl daemon-reload
+ systemctl reload lxcfs.service
Failed to reload lxcfs.service: Unit lxcfs.service not found.
+ CHECK_RESULT 5 0 0 'lxcfs.service reload failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service reload failed'
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'lxcfs.service reload failed'
+ LOG_ERROR 'lxcfs.service reload failed'
+ message='lxcfs.service reload failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'lxcfs.service reload failed'
Wed Dec  7 09:07:17 2022 - ERROR - lxcfs.service reload failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_lxcfs.sh line 35'
+ message='oe_test_service_lxcfs.sh line 35'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_lxcfs.sh line 35'
Wed Dec  7 09:07:17 2022 - ERROR - oe_test_service_lxcfs.sh line 35
+ return 0
+ systemctl status lxcfs.service
+ grep 'Active: active'
Unit lxcfs.service could not be found.
+ CHECK_RESULT 1 0 0 'lxcfs.service reload causes the service status to change'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service reload causes the service status to change'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'lxcfs.service reload causes the service status to change'
+ LOG_ERROR 'lxcfs.service reload causes the service status to change'
+ message='lxcfs.service reload causes the service status to change'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'lxcfs.service reload causes the service status to change'
Wed Dec  7 09:07:18 2022 - ERROR - lxcfs.service reload causes the service status to change
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_lxcfs.sh line 37'
+ message='oe_test_service_lxcfs.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_lxcfs.sh line 37'
Wed Dec  7 09:07:19 2022 - ERROR - oe_test_service_lxcfs.sh line 37
+ return 0
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Wed Dec  7 09:07:19 2022 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 8
+ test 8 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Dec  7 09:07:20 2022 - ERROR - failed to execute the case.
+ exit 8
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Wed Dec  7 09:07:21 2022 - INFO  - start environment cleanup.
+ sed -i 'sExecStart=/usr/bin/lxcfs -d\ExecStart=/usr/bin/lxcfs\g' /usr/lib/systemd/system/lxcfs.service
sed: -e expression #1, char 55: unterminated `s' command
+ systemctl daemon-reload
+ systemctl reload lxcfs.service
Failed to reload lxcfs.service: Unit lxcfs.service not found.
+ systemctl stop lxcfs.service
Failed to stop lxcfs.service: Unit lxcfs.service not loaded.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Wed Dec  7 09:07:24 2022 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Wed Dec  7 09:07:24 2022 - INFO  - Finish environment cleanup!
