+ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n '' ']'
+ trap POST_TEST_DEFAULT EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Dec 23 03:32:39 2022 - INFO  - Start to run test.
+ service auditd restart
oe_test_audit_show_event_list.sh: line 25: service: command not found
+ aureport -e -ts today -te today
Fri Dec 23 04:02:36 2022 - ERROR - Timeout : Command 'bash -x oe_test_audit_show_event_list.sh' timed out after 1799.997825407001 seconds

Event Report
===================================
# date time event type auid success
===================================
<no events of interest were found>

++ POST_TEST_DEFAULT
++ LOG_INFO 'oe_test_audit_show_event_list.sh post_test'
++ message='oe_test_audit_show_event_list.sh post_test'
++ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'oe_test_audit_show_event_list.sh post_test'
Fri Dec 23 06:26:48 2022 - INFO  - oe_test_audit_show_event_list.sh post_test
+ CHECK_RESULT 1 0 0 'aureport failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='aureport failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'aureport failed'
+ LOG_ERROR 'aureport failed'
+ message='aureport failed'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'aureport failed'
Fri Dec 23 06:26:52 2022 - ERROR - aureport failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_audit_show_event_list.sh line 27'
+ message='oe_test_audit_show_event_list.sh line 27'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_audit_show_event_list.sh line 27'
Fri Dec 23 06:26:56 2022 - ERROR - oe_test_audit_show_event_list.sh line 27
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Dec 23 06:26:59 2022 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 1
+ test 1 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Dec 23 06:27:03 2022 - ERROR - failed to execute the case.
+ exit 1
+ POST_TEST_DEFAULT
+ LOG_INFO 'oe_test_audit_show_event_list.sh post_test'
+ message='oe_test_audit_show_event_list.sh post_test'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'oe_test_audit_show_event_list.sh post_test'
Fri Dec 23 06:27:06 2022 - INFO  - oe_test_audit_show_event_list.sh post_test
