+ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n '' ']'
+ trap POST_TEST_DEFAULT EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Dec 23 01:30:22 2022 - INFO  - Start to run test.
+ service auditd restart
oe_test_audit_use_d_audit.sh: line 25: service: command not found
+ auditctl -D
No rules
+ CHECK_RESULT 0 0 0 'delete failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ auditctl -a always,exit -F arch=b64 -S settimeofday -k time_change
arch elf mapping not found
+ CHECK_RESULT 255 0 0 'add failed'
+ actual_result=255
+ expect_result=0
+ mode=0
+ error_log='add failed'
+ '[' -z 255 ']'
+ '[' 0 -eq 0 ']'
+ test 255x '!=' 0x
+ test -n 'add failed'
+ LOG_ERROR 'add failed'
+ message='add failed'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'add failed'
Fri Dec 23 01:30:23 2022 - ERROR - add failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_audit_use_d_audit.sh line 29'
+ message='oe_test_audit_use_d_audit.sh line 29'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_audit_use_d_audit.sh line 29'
Fri Dec 23 01:30:23 2022 - ERROR - oe_test_audit_use_d_audit.sh line 29
+ return 0
+ auditctl -l
+ grep -e '-a always,exit -F arch=b64 -S settimeofday -F key=time_change'
+ CHECK_RESULT 1 0 0 'grep failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='grep failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'grep failed'
+ LOG_ERROR 'grep failed'
+ message='grep failed'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'grep failed'
Fri Dec 23 01:30:24 2022 - ERROR - grep failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_audit_use_d_audit.sh line 31'
+ message='oe_test_audit_use_d_audit.sh line 31'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_audit_use_d_audit.sh line 31'
Fri Dec 23 01:30:25 2022 - ERROR - oe_test_audit_use_d_audit.sh line 31
+ return 0
+ auditctl -d always,exit -F arch=b64 -S settimeofday -k time_change
arch elf mapping not found
+ CHECK_RESULT 255 0 0 'delete failed'
+ actual_result=255
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ '[' -z 255 ']'
+ '[' 0 -eq 0 ']'
+ test 255x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Fri Dec 23 01:30:26 2022 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_audit_use_d_audit.sh line 33'
+ message='oe_test_audit_use_d_audit.sh line 33'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_audit_use_d_audit.sh line 33'
Fri Dec 23 01:30:26 2022 - ERROR - oe_test_audit_use_d_audit.sh line 33
+ return 0
+ auditctl -l
+ grep -e '-a always,exit -F arch=b64 -S settimeofday -F key=time_change'
+ CHECK_RESULT 1 1 0 'grep delete failed'
+ actual_result=1
+ expect_result=1
+ mode=0
+ error_log='grep delete failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 1x
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Dec 23 01:30:27 2022 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 3
+ test 3 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Dec 23 01:30:28 2022 - ERROR - failed to execute the case.
+ exit 3
+ POST_TEST_DEFAULT
+ LOG_INFO 'oe_test_audit_use_d_audit.sh post_test'
+ message='oe_test_audit_use_d_audit.sh post_test'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'oe_test_audit_use_d_audit.sh post_test'
Fri Dec 23 01:30:28 2022 - INFO  - oe_test_audit_use_d_audit.sh post_test
